name: Run Playwright and API tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest-html
        playwright install chromium

    - name: Start Flask API
      run: |
        nohup python api/app.py &
        sleep 5

    - name: Run all tests and generate report
      run: |
        pytest apitests/ uitests/ --html=report.html --self-contained-html

    - name: Upload HTML test report
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: report.html